name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Application
        path: /home/runner/work/AzureDbUp/AzureDbUp/bin/Debug/net5.0/publish/
        
    - name: Create release
    - uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: /home/runner/work/AzureDbUp/AzureDbUp/bin/Debug/net5.0/publish/
